#!/usr/bin/python3

import sys

def fc():
    """
    Function to search file to convert number and format n=p*q
    """
    try:
        revfile = sys.argv[1]
        with open(revfile) as f:
            for revnumber in f:
                revnumber = int(revnumber)
                if revnumber % 2 == 0:
                    print("{}={}*{}".format(revnumber, revnumber // 2, 2))
                    continue
                
                for i in range(3, revnumber // 2 + 1, 2):
                    if revnumber % i == 0:
                        print("{}={}*{}".format(revnumber, revnumber // i, i))
                        break
                else:
                    print("{}={}*{}".format(revnumber, revnumber, 1))
    except IndexError:
        pass
    except FileNotFoundError:
        print("File not found.")
    except ValueError:
        print("Invalid input in the file.")

# autostart
fc()
